// Structure
export const ADD_STRUCTURE = 'ADD_STRUCTURE';
export const STRUCTURE_TYPE = 'STRUCTURE_TYPE';
export const STRUCTURE_NAME = 'STRUCTURE_NAME';
export const STRUCTURE_ID = 'STRUCTURE_ID';
export const STRUCTURE_WEIGHT = 'STRUCTURE_WEIGHT';
export const DRAWING_NO = 'DRAWING_NO';
export const RESET_STRUCTURE_FORM = 'RESET_STRUCTURE_FORM';
export const NUMBER_OF_ATTRIBUTES = 'NUMBER_OF_ATTRIBUTES';

//Add Users

export const FIRST_NAME = 'FIRST_NAME';
export const LAST_NAME = 'LAST_NAME';
export const EMAIL = 'EMAIL';
export const PS_NO = 'PS_NO';
export const PROJECT = 'PROJECT';
export const USER_ROLE = 'USER_ROLE';



//Component
export const COMPONENT_TYPE="COMPONENT_TYPE";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const LIST_COMPONENT = "LIST_COMPONENT";
export const CHANGE_ADD_COMPONENT_MODAL_STATUS="CHANGE_ADD_COMPONENT_MODAL_STATUS";
export const SHOW_ADD_COMPONENT_MSG="SHOW_ADD_COMPONENT_MSG";
export const ADD_COMPONENT_TYPE="ADD_COMPONENT_TYPE";
// IC & BU

export const INDEPENDENT_COMPANY="INDEPENDENT_COMPANY";
export const BUSINESS_UNIT="BUSINESS_UNIT";

//Add Project

export const PROJECT_NAME="PROJECT_NAME";
export const SEGMENT="SEGMENT";
export const AREA="AREA";
export const PROJECT_BUSINESS_UNIT="PROJECT_BUSINESS_UNIT";
export const SITE_LOCATION="SITE_LOCATION";
export const PROJECT_INDEPENDENT_COMPANY="PROJECT_INDEPENDENT_COMPANY";

//Sub Contractor
export const VENDOR_NAME="VENDOR_NAME";
export const VENDOR_CODE="VENDOR_CODE";
export const VENDOR_EMAIL="VENDOR_EMAIL";
export const VENDOR_CONTACT_NUMBER="VENDOR_CONTACT_NUMBER";

//Add Work Break
export const WORK_BREAK_PROJECT_NAME="PROJECT_NAME";

// Assign Structure
export const CAPACITY="CAPACITY";
export const OVER_ALL_LENGTH="OVER_ALL_LENGTH";
export const UNDER_SLING_OVER_SLUNG="UNDER_SLING_OVER_SLUNG";
export const ESTIMATED_WEIGHT="ESTIMATED_WEIGHT";
export const DIAMENSION_LENGTH="DIAMENSION_LENGTH";
export const DIAMENSION_HEIGHT="DIAMENSION_HEIGHT";
export const DIAMENSION_WIDTH="DIAMENSION_WIDTH";
export const NUMBER_OF_COMPONENTS="NUMBER_OF_COMPONENTS";

//Add Requirment

export const QUANTITY="QUANTITY";
export const REQUIRED_FOR_WORK_BREAK="REQUIRED_FOR_WORK_BREAK";
export const REQUIRED_BY="REQUIRED_BY";
export const ACTUAL_WORK_BREAK="ACTUAL_WORK_BREAK";
export const PLANNED_START_DATE="PLANNED_START_DATE";
export const ACTUAL_START_DATE_OF_USAGE="ACTUAL_START_DATE_OF_USAGE";
export const PLANNED_RELEASE_DATE="PLANNED_RELEASE_DATE";
export const EXPECTED_RELEASE_DATE="EXPECTED_RELEASE_DATE";
export const MR_NUMBER="MR_NUMBER";
export const REMARKS="REMARKS";

//Dispatch Management

export const SITE_NAME="SITE_NAME";
export const DATE_OF_REQUEST="DATE_OF_REQUEST";
export const REQUEST_RAISED_BY="REQUEST_RAISED_BY";
export const STRUCTURE_FAMILY = 'STRUCTURE_FAMILY';
export const QUANTITY_REQUESTED = 'QUANTITY_REQUESTED';
export const DISPATCH_ADVICE_NUMBER = 'DISPATCH_ADVICE_NUMBER';

// New Fabrication

export const DC_NUMBER = 'DC_NUMBER';
export const VENDOR = 'VENDOR';
export const DISPATCHED_DATE = 'DISPATCHED_DATE';
export const TO_SITE = 'TO_SITE';
export const QUANTITY_DISPATCHED = 'QUANTITY_DISPATCHED';
export const WORK_ORDER = 'WORK_ORDER';

//Out Source
export const MONTHLY_HIRE_CHARGES = 'MONTHLY_HIRE_CHARGES';

//Scrap

export const AUCTION_ID = 'AUCTION_ID';
export const SCRAP_RATE = 'SCRAP_RATE';

//Modification Management

export const DISPATCHED_FROM = 'DISPATCHED_FROM';
export const RECEIVED_AT = 'RECEIVED_AT';
export const LENGTH = 'LENGTH';
export const WIDTH = 'WIDTH';
export const HEIGHT = 'HEIGHT';
export const BREADTH = 'BREADTH';
export const WEIGHT = 'WEIGHT';
export const COMPONENT_NAME = 'COMPONENT_NAME';
export const COMPONENT_ID = 'COMPONENT_ID';
export const ADDITIONAL_PLATES = 'ADDITIONAL_PLATES';

//Procurement

export const FABRICATION_COST = 'FABRICATION_COST';

//OutSourcing

export const MONTHLY_RENT = 'MONTHLY_RENT';
export const CONTRACT_YEARS = 'CONTRACT_YEARS';

//TransferPrice

export const FROM_SITE = 'FROM_SITE';
export const DISPATCHED_ON = 'DISPATCHED_ON';
export const TRANSFER_PRICE = 'TRANSFER_PRICE';

// Reuse
export const THICKNESS = 'THICKNESS';
export const REUSE_WEIGHT = 'REUSE_WEIGHT';
export const PROPOSED_REUSABILITY = 'PROPOSED_REUSABILITY';
export const YEAR_OF_FABRICATION = 'YEAR_OF_FABRICATION';
export const VENDOR_DETAILS = 'VENDOR_DETAILS';
export const QR_CODE_DETAILS = 'QR_CODE_DETAILS';
export const DEPRECIATION_RATE = 'DEPRECIATION_RATE';
export const BOOK_VALUE = 'BOOK_VALUE';

//Inititing Reuse

export const DISPATCH = 'DISPATCH';

//InitiatePhysicalVerification

export const INSPECTION_ID = 'INSPECTION_ID';


















