// Structure
export const ADD_STRUCTURE = "ADD_STRUCTURE";
export const STRUCTURE_TYPE = "STRUCTURE_TYPE";
export const STRUCTURE_NAME = "STRUCTURE_NAME";
export const STRUCTURE_ID = "STRUCTURE_ID";
export const STRUCTURE_WEIGHT = "STRUCTURE_WEIGHT";
export const DRAWING_NO = "DRAWING_NO";
export const RESET_STRUCTURE_FORM = "RESET_STRUCTURE_FORM";
export const NUMBER_OF_ATTRIBUTES = "NUMBER_OF_ATTRIBUTES";
export const LIST_STRUCTURE = "LIST_STRUCTURE";
export const CHANGE_ADD_STRUCTURE_MODAL_STATUS =
  "CHANGE_ADD_STRUCTURE_MODAL_STATUS";
export const SHOW_ADD_STRUCTURE_MSG = "SHOW_ADD_STRUCTURE_MSG";
export const STRUCTURE_ATTRIBUTE_LIST = "STRUCTURE_ATTRIBUTE_LIST";
export const STRUCTURE_EDIT_PAGE = "STRUCTURE_EDIT_PAGE";
export const GET_STRUCTURE_DATA = "GET_STRUCTURE_DATA";
export const UPDATE_STRUCTURE = "UPDATE_STRUCTURE";
//Add Users

export const FIRST_NAME = "FIRST_NAME";
export const LAST_NAME = "LAST_NAME";
export const EMAIL = "EMAIL";
export const PS_NO = "PS_NO";
export const PROJECT = "PROJECT";
export const USER_ROLE = "USER_ROLE";
export const LIST_USERS = "LIST_USERS";
export const SHOW_ADD_USERS_MSG = "SHOW_ADD_USERS_MSG";
export const CHANGE_ADD_USERS_MODAL_STATUS = "CHANGE_ADD_USERS_MODAL_STATUS";
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
export const GET_ROLES_LIST = "GET_ROLES_LIST";
export const ADD_USER = "ADD_USER";
export const RESET_CREATE_USER_FORM = "RESET_CREATE_USER_FORM";
export const GET_USER_SINGLE = "GET_USER_SINGLE";
export const USER_EDIT_PAGE = "USER_EDIT_PAGE";
export const UPDATE_USER = "UPDATE_USER";
export const JOB_CODE = "JOB_CODE";
export const EDRC_CODE = "EDRC_CODE";
//Component
export const COMPONENT_TYPE = "COMPONENT_TYPE";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const LIST_COMPONENT = "LIST_COMPONENT";
export const CHANGE_ADD_COMPONENT_MODAL_STATUS =
  "CHANGE_ADD_COMPONENT_MODAL_STATUS";
export const SHOW_ADD_COMPONENT_MSG = "SHOW_ADD_COMPONENT_MSG";
export const ADD_COMPONENT_TYPE = "ADD_COMPONENT_TYPE";
export const SET_COMPONENT_EDIT_MODE = "SET_COMPONENT_EDIT_MODE";
export const GET_COMPONENT_TYPE = "GET_COMPONENT_TYPE";
export const COMPONENT_TYPE_STATUS = "COMPONENT_TYPE_STATUS";
export const UPDATE_COMPONENT_TYPE = "UPDATE_COMPONENT_TYPE";
export const RESET_CREATE_COMPONENT_TYPE_FORM =
  "RESET_CREATE_COMPONENT_TYPE_FORM";
export const COMPONENT_TYPE_LOADING = "COMPONENT_TYPE_LOADING";
// IC

export const INDEPENDENT_COMPANY = "INDEPENDENT_COMPANY";
export const BUSINESS_UNIT = "BUSINESS_UNIT";
export const ADD_INDEPENDENT_COMPANY = "ADD_INDEPENDENT_COMPANY";
export const IC_DESCRIPTION = "IC_DESCRIPTION";
export const RESET_IC_FORM = "RESET_IC_FORM";
export const IC_TYPE = "IC_TYPE";
export const BU_TYPE = "BU_TYPE";
export const IC_NAME = "IC_NAME";
export const BU_NAME = "BU_NAME";
export const SHOW_ADD_ICBU_MODAL = "SHOW_ADD_ICBU_MODAL";
export const SHOW_ADD_ICBU_MSG = "SHOW_ADD_ICBU_MSG";
export const RESET_ICBU_FORM = "SHOW_ADD_ICBU_MSG";
export const SHOW_ICBU_MSG = "SHOW_ICBU_MSG";

export const LIST_ICBU = "LIST_ICBU";
export const GET_SINGLE_ICBU = "GET_SINGLE_ICBU";
export const CREATE_ICBU = "CREATE_ICBU";
export const UPDATE_ICBU = "UPDATE_ICBU";
export const EDIT_SINGLE_BU = "EDIT_SINGLE_BU";
//Business Unit

export const BUSINESS_UNIT_TYPE = "BUSINESS_UNIT_TYPE";
export const BUSINESS_UNIT_STATUS = "BUSINESS_UNIT_STATUS";
export const CHANGE_ADD_BUSINESS_UNIT_MODAL_STATUS =
  "CHANGE_ADD_BUSINESS_UNIT_MODAL_STATUS";
export const SHOW_ADD_BUSINESS_UNIT_MSG = "SHOW_ADD_BUSINESS_UNIT_MSG";
export const SHOW_ADD_BUSINESS_UNIT_MODAL = "SHOW_ADD_BUSINESS_UNIT_MODAL";
export const RESET_CREATE_BUSINESS_UNIT_FORM =
  "RESET_CREATE_BUSINESS_UNIT_FORM";
export const SET_BUSINESS_UNIT_EDIT_MODE = "SET_BUSINESS_UNIT_EDIT_MODE";
export const BUSINESS_UNIT_NAME = "BUSINESS_UNIT_NAME";
export const LIST_IC_CODES = "LIST_IC_CODES";
export const LIST_BUSINESS_UNIT = "LIST_BUSINESS_UNIT";
export const ADD_BUSINESS_UNIT = "ADD_BUSINESS_UNIT";
export const UPDATE_BUSINESS_UNIT = "UPDATE_BUSINESS_UNIT";
export const GET_BUSINESS_UNIT_TYPE = "GET_BUSINESS_UNIT_TYPE";
export const UPDATE_BUSINESS_UNIT_NAME = "UPDATE_BUSINESS_UNIT_NAME";
export const IC_CODE = "";
export const BUSINESS_UNIT_LIST = "BUSINESS_UNIT_LIST";
export const CHANGE_EDIT_BUSINESS_UNIT_MODAL_STATUS =
  "CHANGE_EDIT_BUSINESS_UNIT_MODAL_STATUS";
export const RESET_EDIT_BUSINESS_UNIT_FORM = "RESET_EDIT_BUSINESS_UNIT_FORM";

//Add Project

export const PROJECT_NAME = "PROJECT_NAME";
export const SEGMENT = "SEGMENT";
export const AREA = "AREA";
export const PROJECT_BUSINESS_UNIT = "PROJECT_BUSINESS_UNIT";
export const SITE_LOCATION = "SITE_LOCATION";
export const PROJECT_INDEPENDENT_COMPANY = "PROJECT_INDEPENDENT_COMPANY";

export const RESET_PROJECT_FORM = "RESET_PROJECT_FORM";
export const LIST_PROJECT = "LIST_PROJECT";
export const SHOW_ADD_PROJ_MODAL = "SHOW_ADD_PROJ_MODAL";
export const SET_EDIT_MODE = "SET_EDIT_MODE";
export const GET_SINGLE_PROJ = "GET_SINGLE_PROJ";
export const GET_SEGMENT_LIST = "GET_SEGMENT_LIST";
export const GET_IC_LIST = "GET_IC_LIST";
export const GET_BU_LIST = "GET_BU_LIST";
export const ON_CHANGE_SEGMENT = "ON_CHANGE_SEGMENT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const SHOW_ERR_MSG = "SHOW_ERR_MSG";
export const ADD_LOCATION_FIELD = "ADD_LOCATION_FIELD";

//Sub Contractor
export const VENDOR_NAME = "VENDOR_NAME";
export const VENDOR_CODE = "VENDOR_CODE";
export const VENDOR_EMAIL = "VENDOR_EMAIL";
export const VENDOR_CONTACT_NUMBER = "VENDOR_CONTACT_NUMBER";
export const VENDOR_LIST = "VENDOR_LIST";
export const VENDOR_STATUS = "VENDOR_STATUS";

export const LIST_VENDOR = "LIST_VENDOR";
export const GET_SINGLE_VENDOR = "GET_SINGLE_VENDOR";
export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const CREATE_VENDOR = "CREATE_VENDOR";

export const SHOW_ADD_VENDOR_MODAL = "SHOW_ADD_VENDOR_MODAL";
export const RESET_VENDOR_FORM = "RESET_VENDOR_FORM";
export const SHOW_ADD_VENDOR_MSG = "SHOW_ADD_VENDOR_MSG";

//Add Work Break
export const WORK_BREAK_PROJECT_NAME = "PROJECT_NAME";
export const WBS_UPLOADED_DATA = "WBS_UPLOADED_DATA";
export const RESET_WBS_FORM = "RESET_WBS_FORM";
export const LIST_PROJECT_CODES = "LIST_PROJECT_CODES";
export const SAVE_WBS_DATA = "SAVE_WBS_DATA";
export const LIST_WBS_DATA = "LIST_WBS_DATA";
export const SINGLE_WBS_DATA = "SINGLE_WBS_DATA";
// Assign Structure
export const CAPACITY = "CAPACITY";
export const OVER_ALL_LENGTH = "OVER_ALL_LENGTH";
export const UNDER_SLING_OVER_SLUNG = "UNDER_SLING_OVER_SLUNG";
export const ESTIMATED_WEIGHT = "ESTIMATED_WEIGHT";
export const DIAMENSION_LENGTH = "DIAMENSION_LENGTH";
export const DIAMENSION_HEIGHT = "DIAMENSION_HEIGHT";
export const DIAMENSION_WIDTH = "DIAMENSION_WIDTH";
export const NUMBER_OF_COMPONENTS = "NUMBER_OF_COMPONENTS";
export const LIST_ASSIGN_STRUCTURE = "LIST_ASSIGN_STRUCTURE";
export const ASSIGN_STRUCTURE_MORE_PAGE = "ASSIGN_STRUCTURE_MORE_PAGE";
export const CHANGE_ASSIGN_STRUCTURE_MORE_MODAL_STATUS =
  "CHANGE_ASSIGN_STRUCTURE_MORE_MODAL_STATUS";
export const GET_ASSIGN_STRUCTURE_DATA_SINGLE =
  "GET_ASSIGN_STRUCTURE_DATA_SINGLE";
export const LIST_ASSIGN_COMPONENT = "LIST_ASSIGN_COMPONENT";
export const CHANGE_ASSIGN_COMPONENT_MORE_MODAL_STATUS =
  "CHANGE_ASSIGN_COMPONENT_MORE_MODAL_STATUS";
export const GET_ASSIGN_COMPONENT_DATA_SINGLE =
  "GET_ASSIGN_COMPONENT_DATA_SINGLE";
export const ASSIGN_COMPONENT_MORE_PAGE = "ASSIGN_COMPONENT_MORE_PAGE";
export const SET_PROJECT_STRUCTURE_ID = "SET_PROJECT_STRUCTURE_ID";
//Add Requirment

export const QUANTITY = "QUANTITY";
export const REQUIRED_FOR_WORK_BREAK = "REQUIRED_FOR_WORK_BREAK";
export const REQUIRED_BY = "REQUIRED_BY";
export const ACTUAL_WORK_BREAK = "ACTUAL_WORK_BREAK";
export const PLANNED_START_DATE = "PLANNED_START_DATE";
export const ACTUAL_START_DATE_OF_USAGE = "ACTUAL_START_DATE_OF_USAGE";
export const PLANNED_RELEASE_DATE = "PLANNED_RELEASE_DATE";
export const EXPECTED_RELEASE_DATE = "EXPECTED_RELEASE_DATE";
export const MR_NUMBER = "MR_NUMBER";
export const REMARKS = "REMARKS";
export const LIST_WBS_CODES = "LIST_WBS_CODES";
export const SITE_REQUIRMENT_LIST = "SITE_REQUIRMENT_LIST";
export const ADD_REQUIREMENT = "ADD_REQUIREMENT";
export const RESET_REQUIREMENT_FORM = "RESET_REQUIREMENT_FORM";
export const LIST_STRUCTURE_PROJECT_DATA = "LIST_STRUCTURE_PROJECT_DATA";
export const LIST_REQUIREMENTS = "LIST_REQUIREMENTS";
export const ACTION_REQUIREMENT = "ACTION_REQUIREMENT";
export const GET_REQUIREMENT_DATA_SINGLE = "GET_REQUIREMENT_DATA_SINGLE";
export const VIEW_REQUIREMENTS_MORE_PAGE = "VIEW_REQUIREMENTS_MORE_PAGE";
export const CHANGE_VIEW_REQUIREMENTS_MORE_MODAL_STATUS =
  "CHANGE_VIEW_REQUIREMENTS_MORE_MODAL_STATUS";
export const SHOW_MODAL = "SHOW_MODAL";

//Dispatch Management

export const SITE_NAME = "SITE_NAME";
export const DATE_OF_REQUEST = "DATE_OF_REQUEST";
export const REQUEST_RAISED_BY = "REQUEST_RAISED_BY";
export const STRUCTURE_FAMILY = "STRUCTURE_FAMILY";
export const QUANTITY_REQUESTED = "QUANTITY_REQUESTED";
export const DISPATCH_ADVICE_NUMBER = "DISPATCH_ADVICE_NUMBER";

// New Fabrication

export const DC_NUMBER = "DC_NUMBER";
export const VENDOR = "VENDOR";
export const DISPATCHED_DATE = "DISPATCHED_DATE";
export const TO_SITE = "TO_SITE";
export const QUANTITY_DISPATCHED = "QUANTITY_DISPATCHED";
export const WORK_ORDER = "WORK_ORDER";

//Out Source
export const MONTHLY_HIRE_CHARGES = "MONTHLY_HIRE_CHARGES";

//Scrap

export const AUCTION_ID = "AUCTION_ID";
export const SCRAP_RATE = "SCRAP_RATE";
export const ACTION_SCRAP = "ACTION_SCRAP";
export const SCRAP_STRUCTURE_ID = "SCRAP_STRUCTURE_ID";
export const SCRAP_DATE = "SCRAP_DATE";
export const SCRAP_UPLOAD = "SCRAP_UPLOAD";
export const SCRAP_LIST_STRUCTURE_PROJECT_DATA =
  "SCRAP_LIST_STRUCTURE_PROJECT_DATA";
// export const LIST_PROJECT_CODES="LIST_PROJECT_CODES";
export const SCRAP_PROJECT_ID = "SCRAP_PROJECT_ID";
export const ADD_SCRAP = "ADD_SCRAP";
export const RESET_SCRAP_FORM = "RESET_SCRAP_FORM";
export const SCRAP_FILE = "SCRAP_FILE";
export const SCRAP_STRUCTURE_FAMILY = "SCRAP_STRUCTURE_FAMILY";
export const SCRAP_APPROVAL_LIST = "SCRAP_APPROVAL_LIST";
export const CHANGE_VIEW_SCRAP_MORE_MODAL_STATUS =
  "CHANGE_VIEW_SCRAP_MORE_MODAL_STATUS";
export const GET_SCRAP_DATA_SINGLE = "GET_SCRAP_DATA_SINGLE";
export const VIEW_SCRAP_MORE_PAGE = "VIEW_SCRAP_MORE_PAGE";
export const SCRAP_STRUCTURE_CODE = "SCRAP_STRUCTURE_CODE";
export const LIST_SCRAP_CODES = "LIST_SCRAP_CODES";
export const SCRAP_VENDOR = "SCRAP_VENDOR";
export const SCRAP_AUCTION_ID = "SCRAP_AUCTION_ID";

//Modification Management

export const DISPATCHED_FROM = "DISPATCHED_FROM";
export const RECEIVED_AT = "RECEIVED_AT";
export const LENGTH = "LENGTH";
export const WIDTH = "WIDTH";
export const HEIGHT = "HEIGHT";
export const BREADTH = "BREADTH";
export const WEIGHT = "WEIGHT";
export const COMPONENT_NAME = "COMPONENT_NAME";
export const COMPONENT_ID = "COMPONENT_ID";
export const ADDITIONAL_PLATES = "ADDITIONAL_PLATES";

//Procurement

// export const FABRICATION_COST = "FABRICATION_COST";

//OutSourcing

export const MONTHLY_RENT = "MONTHLY_RENT";
export const CONTRACT_YEARS = "CONTRACT_YEARS";

//TransferPrice

export const FROM_SITE = "FROM_SITE";
export const DISPATCHED_ON = "DISPATCHED_ON";
export const TRANSFER_PRICE = "TRANSFER_PRICE";
export const ADD_TRANSFER_PRICE = "ADD_TRANSFER_PRICE";

// Reuse
export const THICKNESS = "THICKNESS";
export const REUSE_WEIGHT = "REUSE_WEIGHT";
export const PROPOSED_REUSABILITY = "PROPOSED_REUSABILITY";
export const YEAR_OF_FABRICATION = "YEAR_OF_FABRICATION";
export const VENDOR_DETAILS = "VENDOR_DETAILS";
export const QR_CODE_DETAILS = "QR_CODE_DETAILS";
export const DEPRECIATION_RATE = "DEPRECIATION_RATE";
export const BOOK_VALUE = "BOOK_VALUE";

//Inititing Reuse

export const DISPATCH = "DISPATCH";

//InitiatePhysicalVerification

export const INSPECTION_ID = "INSPECTION_ID";

//Add Structure Family
export const SET_STRUCTURE_FAMILY_EDIT_MODE = "SET_STRUCTURE_FAMILY_EDIT_MODE";
export const RESET_CREATE_STRUCTURE_FAMILY_FORM =
  "RESET_CREATE_STRUCTURE_FAMILY_FORM";
export const CHANGE_ADD_STRUCTURE_FAMILY_MODAL_STATUS =
  "CHANGE_ADD_STRUCTURE_FAMILY_MODAL_STATUS";
export const STRUCTURE_FAMILY_TYPE = "STRUCTURE_FAMILY_TYPE";
export const STRUCTURE_FAMILY_TYPE_STATUS = "STRUCTURE_FAMILY_TYPE_STATUS";

export const SHOW_ADD_STRUCTURE_FAMILY_MSG = "SHOW_ADD_STRUCTURE_FAMILY_MSG";
export const CHANGE_STRUCTURE_FAMILY_MODAL_STATUS =
  "CHANGE_STRUCTURE_FAMILY_MODAL_STATUS";
export const ADD_STRUCTURE_FAMILY = "ADD_STRUCTURE_FAMILY";
export const UPDATE_STRUCTURE_FAMILY_TYPE = "UPDATE_STRUCTURE_FAMILY_TYPE";
export const LIST_STRUCTURE_FAMILY = "LIST_STRUCTURE_FAMILY";
export const GET_STRUCTURE_FAMILY_TYPE = "GET_STRUCTURE_FAMILY_TYPE";
export const STRUCTURE_FAMILY_STATUS = "STRUCTURE_FAMILY_STATUS";
export const RESET_CREATE_STRUCTURE_FAMILY_TYPE_FORM =
  "RESET_CREATE_STRUCTURE_FAMILY_TYPE_FORM";
export const ADD_STRUCTURE_FAMILY_TYPE = "ADD_STRUCTURE_FAMILY_TYPE";
export const SHOW_ADD_STRUCTURE_FAMILY_MODAL =
  "SHOW_ADD_STRUCTURE_FAMILY_MODAL";

//Assign Structure
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_STRUCT_LIST = "GET_STRUCT_LIST";
export const SAVE_ASSIGN_STRUCT = "SAVE_ASSIGN_STRUCT";
export const ASSIGN_STRUCT_UPLOADED_DATA = "ASSIGN_STRUCT_UPLOADED_DATA";
export const ASSIGN_FILE_UPLOAD = "ASSIGN_FILE_UPLOAD";
export const ON_CHANGE_ASSIGN_STRUCT = "ON_CHANGE_ASSIGN_STRUCT";
export const GET_ASSIGN_STRUCT_DETAILS_ID = "GET_ASSIGN_STRUCT_DETAILS_ID";
export const ASSIGN_FILE_REMOVE = "ASSIGN_FILE_REMOVE";
export const RESET_ASSIGN_STRUCT_FORM = "RESET_ASSIGN_STRUCT_FORM";
export const SAVE_ASSIGN_COMP = "SAVE_ASSIGN_COMP";
export const RESET_ASSIGN_COMP_FORM = "RESET_ASSIGN_COMP_FORM";

//Auth
export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SET_TOKEN = "SET_TOKEN";
export const RESET_LOGIN_DETAILS = "RESET_LOGIN_DETAILS";
export const SET_PAGE_ACCESS = "SET_PAGE_ACCESS";
export const SET_ROLE_BASED_ROUTE_ACCESS = "SET_ROLE_BASED_ROUTE_ACCESS";

//Surplus
export const SURPLUS_STRUCTURE_ID = "SURPLUS_STRUCTURE_ID";
export const SURPLUS_DATE = "SURPLUS_DATE";
export const SURPLUS_UPLOAD = "SURPLUS_UPLOAD";
export const SURPLUS_PROJECT_ID = "SURPLUS_PROJECT_ID";
export const SURPLUS_LIST_STRUCTURE_PROJECT_DATA =
  "SURPLUS_LIST_STRUCTURE_PROJECT_DATA";
export const RESET_SURPLUS_FORM = "RESET_SURPLUS_FORM";
export const ADD_SURPLUS = "ADD_SURPLUS";
export const SURPLUS_FILE = "SURPLUS_FILE";
export const SURPLUS_STRUCTURE_FAMILY = "SURPLUS_STRUCTURE_FAMILY";
export const SURPLUS_APPROVAL_LIST = "SURPLUS_APPROVAL_LIST";
export const ACTION_SURPLUS = "ACTION_SURPLUS";
export const CHANGE_VIEW_SURPLUS_MORE_MODAL_STATUS =
  "CHANGE_VIEW_SURPLUS_MORE_MODAL_STATUS";
export const GET_SURPLUS_DATA_SINGLE = "GET_SURPLUS_DATA_SINGLE";
export const VIEW_SURPLUS_MORE_PAGE = "VIEW_SURPLUS_MORE_PAGE";
export const SURPLUS_STRUCTURE_CODE = "SURPLUS_STRUCTURE_CODE";

//Vendor
export const ON_CHANGE_VEN_NAME = "ON_CHANGE_VEN_NAME";
export const ON_CHANGE_VEN_CODE = "ON_CHANGE_VEN_CODE";
export const ON_CHANGE_VEN_EMAIL = "ON_CHANGE_VEN_EMAIL";
export const ON_CHANGE_VEN_PHONE_NUM = "ON_CHANGE_VEN_PHONE_NUM";
export const ON_CHANGE_VEN_STS = "ON_CHANGE_VEN_STS";
export const GET_VENDOR_TYPE = "GET_VENDOR_TYPE";
export const ON_CHANGE_VEN_SERV_TYPES = "ON_CHANGE_VEN_SERV_TYPES";

//Site Dispatch
export const SET_SHOW_EDIT_MODAL_FLAG = "SET_SHOW_EDIT_MODAL_FLAG";
export const SET_SITE_DISPATCH_DETAILS = "SET_SITE_DISPATCH_DETAILS";
export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const SET_STRUCTURE_LIST_CODE = "SET_STRUCTURE_LIST_CODE";
export const SET_STRUCTURE_ID = "SET_STRUCTURE_ID";
export const SET_DISPATCH_DATE = "SET_DISPATCH_DATE";
export const SET_WORK_ORDER_NUMBER = "SET_WORK_ORDER_NUMBER";
export const SET_UPLOADED_FILE = "SET_UPLOADED_FILE";
export const UPDATE_SITE_DISPATCH = "UPDATE_SITE_DISPATCH";
export const RESET_UPDATE_SITE_DISPATCH_MODAL =
  "RESET_UPDATE_SITE_DISPATCH_MODAL";

//Procurement
export const RESET_MESSAGE = "RESET_MESSAGE";
export const SET_VENDOR_CODE_LIST = "SET_VENDOR_CODE_LIST";
export const SET_FABRICATION_COST = "SET_FABRICATION_COST";
export const SET_MONTHLY_RENT = "SET_MONTHLY_RENT";
export const SET_CONTRACT_YEARS = "SET_CONTRACT_YEARS";
export const SET_PLANNED_RELEASE_DATE = "SET_PLANNED_RELEASE_DATE";
export const SET_ACTUAL_START_DATE = "SET_ACTUAL_START_DATE";
export const SET_EXPECTED_RELEASE_DATE = "SET_EXPECTED_RELEASE_DATE";
export const SET_VENDOR = "SET_VENDOR";
export const SET_SHOW_TABLE_FLAG = "SET_SHOW_TABLE_FLAG";
export const SET_VENDOR_STRUCTURES = "SET_VENDOR_SRUCTURES";
export const SET_SELECTED_STRUCTURES = "SET_SELECTED_STRUCTURES";
export const POST_ASSIGN_VENDOR = "POST_ASSIGN_VENDOR";
export const RESET_ASSIGN_VENDOR_MODAL = "RESET_ASSIGN_VENDOR_MODAL";

// Transfer Price
export const RESET_UPDATE_TRANSFER_PRICE_MODAL =
  "RESET_UPDATE_TRANSFER_PRICE_MODAL";
export const SET_TRANSFER_PRICE_DETAILS = "SET_TRANSFER_PRICE_DETAILS";
export const RESET_TRANSFER_PRICE_MODAL = "RESET_TRANSFER_PRICE_MODAL";
export const SET_SHOW_MORE_MODAL_FLAG = "SET_SHOW_MORE_MODAL_FLAG";
export const RESET_TRANSFER_PRICE_VIEW_MORE_MODAL =
  "RESET_TRANSFER_PRICE_VIEW_MORE_MODAL";
export const CHANGE_ADD_TRANSFER_PRICE_MODAL_STATUS =
  "CHANGE_ADD_TRANSFER_PRICE_MODAL_STATUS";
export const DISPATCH_REQUEST_ID = "DISPATCH_REQUEST_ID";

//New Fabrication : Site Approval

export const SET_SITE_APPROVAL_DETAILS = "SET_SITE_APPROVAL_DETAILS";
export const RESET_UPDATE_SITE_APPROVAL_MODAL =
  "RESET_UPDATE_SITE_APPROVAL_MODAL";
export const RESET_SITE_APPROVAL_VIEW_MORE_MODAL =
  "RESET_SITE_APPROVAL_VIEW_MORE_MODAL";
export const CHANGE_VIEW_SITE_APPROVAL_MORE_MODAL_STATUS =
  "CHANGE_VIEW_SITE_APPROVAL_MORE_MODAL_STATUS";
export const ACTION_SITE_APPROVAL = "ACTION_SITE_APPROVAL";
export const GET_SITE_APPROVAL_DATA_SINGLE = "GET_SITE_APPROVAL_DATA_SINGLE";
export const SET_SITE_APPROVAL_MORE_DETAILS = "SET_SITE_APPROVAL_MORE_DETAILS";

//New Fabrication : Vendor

export const SET_NEW_FABRICATION_VENDOR_DETAILS =
  "SET_NEW_FABRICATION_VENDOR_DETAILS";
export const SET_TO_SITE = "SET_TO_SITE";
export const SET_STRUCTURE = "SET_STRUCTURE";
export const SET_QUANTITY_DISPATCHED = "SET_QUANTITY_DISPATCHED";
export const SET_WORK_ORDER = "SET_WORK_ORDER";
export const SET_SHOW_DISPATCH_MODAL_FLAG = "SET_SHOW_DISPATCH_MODAL_FLAG";
export const RESET_NEW_FABRICATION_VENDOR_MODAL =
  "RESET_NEW_FABRICATION_VENDOR_MODAL";
export const UPDATE_VENDOR_DETAILS = "UPDATE_VENDOR_DETAILS";
export const SET_STRUCTURE_NAME = "SET_STRUCTURE_NAME";
export const ACTION_SITE_DECLINE = "ACTION_SITE_DECLINE";

//Out Sourcing : Site Approval

export const SET_OUT_SOURCING_SITE_APPROVAL_DETAILS =
  "SET_OUT_SOURCING_SITE_APPROVAL_DETAILS";

//Condition Assessment

export const SET_CONDITION_ASSESSMENT_DETAILS =
  "SET_CONDITION_ASSESSMENT_DETAILS";
export const RESET_UPDATE_CONDITION_ASSESSMENT_MODAL =
  "RESET_UPDATE_CONDITION_ASSESSMENT_MODAL";
export const GET_CONDITION_ASSESSMENT_DATA_SINGLE =
  "GET_CONDITION_ASSESSMENT_DATA_SINGLE";
export const ACTION_CONDITION_ASSESSMENT = "ACTION_CONDITION_ASSESSMENT";

//Form Site Approval

export const SET_FROM_SITE_APPROVAL_DETAILS = "SET_FROM_SITE_APPROVAL_DETAILS";
export const RESET_UPDATE_FROM_SITE_APPROVAL_MODAL =
  "RESET_UPDATE_FROM_SITE_APPROVAL_MODAL";
export const GET_FROM_SITE_APPROVAL_DATA_SINGLE =
  "GET_FROM_SITE_APPROVAL_DATA_SINGLE";
export const ACTION_FROM_SITE_APPROVAL = "ACTION_FROM_SITE_APPROVAL";
export const ACTION_FROM_SITE_DECLINE = "ACTION_FROM_SITE_DECLINE";

//To Site Approval

export const SET_TO_SITE_APPROVAL_DETAILS = "SET_FROM_SITE_APPROVAL_DETAILS";
export const RESET_UPDATE_TO_SITE_APPROVAL_MODAL =
  "RESET_UPDATE_TO_SITE_APPROVAL_MODAL";
export const GET_TO_SITE_APPROVAL_DATA_SINGLE =
  "GET_FROM_SITE_APPROVAL_DATA_SINGLE";
export const ACTION_TO_SITE_APPROVAL = "ACTION_FROM_SITE_APPROVAL";
export const ACTION_TO_SITE_DECLINE = "ACTION_TO_SITE_DECLINE";
//Create dispatch
export const GET_SITE_REQ_DETAILS = "GET_SITE_REQUIREMENT_DETAILS";
export const GET_SITE_REQ_DETAILS_BY_ID = "GET_SITE_REQUIREMENT_DETAILS_BY_ID";
export const SET_SELECTED_ITEMS = "SET_SELECTED_ITEMS";
export const SET_MODAL_DATA = "SET_MODAL_DATA";
export const SET_SERVICE_TYPE_ID = "SET_SERVICE_TYPE_ID";
export const SET_DISPATCH_ERROR = "SET_DISPATCH_ERROR";
export const CREATE_DISPATCH = "CREATE_DISPATCH";
export const RESET_SELECTION = "RESET_SELECTION";

//Physical Verification
export const SET_PHYSICAL_VERIFICATION_DETAILS =
  "SET_PHYSICAL_VERIFICATION_DETAILS";
export const FROM_DUE = "FROM_DUE";
export const TO_DUE = "TO_DUE";
export const RESET_UPDATE_PHYSICAL_VERIFICATION_MODAL =
  "RESET_UPDATE_PHYSICAL_VERIFICATION_MODAL";
export const RESET_PHYSICAL_VERIFICATION_MODAL =
  "RESET_PHYSICAL_VERIFICATION_MODAL";

// TWCC DISPATCH

export const TWCC_DISPATCH_MORE_PAGE = "TWCC_DISPATCH_MORE_PAGE";

// fabrication Cost
export const SET_FABCOST_MODAL_FLAG = "SET_FABCOST_MODAL_FLAG";
export const FABCOST_VIEWMORE_FLAG = "FABCOST_VIEWMORE_FLAG";
export const SET_UPLOAD_DATA = "SET_UPLOAD_DATA";
export const HANDLE_WO_UPLOAD = "HANDLE_WO_UPLOAD";
export const RESET_FABCOST_MODAL = "RESET_FABCOST_MODAL";
export const CHANGE_TWCC_DISPATCH_MORE_MODAL_STATUS =
  "CHANGE_TWCC_DISPATCH_MORE_MODAL_STATUS";

//Built Details
export const CHANGE_ADD_BUILT_MODAL_STATUS = "CHANGE_ADD_BUILT_MODAL_STATUS";
export const SET_BUILT_EDIT_MODE = "SET_BUILT_EDIT_MODE";
export const LIST_BUILT_DETAILS = "LIST_BUILT_DETAILS";
export const BUILT_TYPE_LIST = "BUILT_TYPE_LIST";
export const CHANGE_BUILT_MORE_MODAL_STATUS = "CHANGE_BUILT_MORE_MODAL_STATUS";
export const BUILT_MORE_PAGE = "BUILT_MORE_PAGE";
export const CHANGE_BUILT_EDIT_MORE_MODAL_STATUS =
  "CHANGE_BUILT_EDIT_MORE_MODAL_STATUS";
export const BUILT_EDIT_MORE_PAGE = "BUILT_EDIT_MORE_PAGE";
