// Structure
export const ADD_STRUCTURE = 'ADD_STRUCTURE';
export const STRUCTURE_TYPE = 'STRUCTURE_TYPE';
export const STRUCTURE_NAME = 'STRUCTURE_NAME';
export const STRUCTURE_ID = 'STRUCTURE_ID';
export const STRUCTURE_WEIGHT = 'STRUCTURE_WEIGHT';
export const DRAWING_NO = 'DRAWING_NO';
export const RESET_STRUCTURE_FORM = 'RESET_STRUCTURE_FORM';
export const NUMBER_OF_ATTRIBUTES = 'NUMBER_OF_ATTRIBUTES';
export const LIST_STRUCTURE="LIST_STRUCTURE";
export const CHANGE_ADD_STRUCTURE_MODAL_STATUS="CHANGE_ADD_STRUCTURE_MODAL_STATUS";
export const SHOW_ADD_STRUCTURE_MSG="SHOW_ADD_STRUCTURE_MSG";
export const STRUCTURE_ATTRIBUTE_LIST="STRUCTURE_ATTRIBUTE_LIST";
export const STRUCTURE_EDIT_PAGE="STRUCTURE_EDIT_PAGE";
export const GET_STRUCTURE_DATA="GET_STRUCTURE_DATA";
export const UPDATE_STRUCTURE="UPDATE_STRUCTURE";
//Add Users

export const FIRST_NAME = 'FIRST_NAME';
export const LAST_NAME = 'LAST_NAME';
export const EMAIL = 'EMAIL';
export const PS_NO = 'PS_NO';
export const PROJECT = 'PROJECT';
export const USER_ROLE = 'USER_ROLE';
export const LIST_USERS= "LIST_USERS";
export const SHOW_ADD_USERS_MSG = "SHOW_ADD_USERS_MSG";
export const CHANGE_ADD_USERS_MODAL_STATUS = "CHANGE_ADD_USERS_MODAL_STATUS";
export const GET_PROJECT_DETAILS="GET_PROJECT_DETAILS";
export const GET_ROLES_LIST= "GET_ROLES_LIST";
export const ADD_USER="ADD_USER";
export const RESET_CREATE_USER_FORM="RESET_CREATE_USER_FORM";
export const GET_USER_SINGLE="GET_USER_SINGLE";
export const USER_EDIT_PAGE="USER_EDIT_PAGE";
export const UPDATE_USER="UPDATE_USER";
//Component
export const COMPONENT_TYPE="COMPONENT_TYPE";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const LIST_COMPONENT = "LIST_COMPONENT";
export const CHANGE_ADD_COMPONENT_MODAL_STATUS="CHANGE_ADD_COMPONENT_MODAL_STATUS";
export const SHOW_ADD_COMPONENT_MSG="SHOW_ADD_COMPONENT_MSG";
export const ADD_COMPONENT_TYPE="ADD_COMPONENT_TYPE";
export const SET_COMPONENT_EDIT_MODE="SET_COMPONENT_EDIT_MODE";
export const GET_COMPONENT_TYPE="GET_COMPONENT_TYPE";
export const COMPONENT_TYPE_STATUS="COMPONENT_TYPE_STATUS";
export const UPDATE_COMPONENT_TYPE="UPDATE_COMPONENT_TYPE";
export const RESET_CREATE_COMPONENT_TYPE_FORM="RESET_CREATE_COMPONENT_TYPE_FORM";
export const COMPONENT_TYPE_LOADING="COMPONENT_TYPE_LOADING";
// IC & BU

export const INDEPENDENT_COMPANY="INDEPENDENT_COMPANY";
export const BUSINESS_UNIT="BUSINESS_UNIT";
export const ADD_INDEPENDENT_COMPANY="ADD_INDEPENDENT_COMPANY";

export const IC_TYPE="IC_TYPE";
export const BU_TYPE="BU_TYPE";
export const IC_NAME="IC_NAME";
export const BU_NAME="BU_NAME";
export const SHOW_ADD_ICBU_MODAL="SHOW_ADD_ICBU_MODAL";
export const SHOW_ADD_ICBU_MSG="SHOW_ADD_ICBU_MSG";
export const RESET_ICBU_FORM="SHOW_ADD_ICBU_MSG";
export const SHOW_ICBU_MSG="SHOW_ICBU_MSG";

export const LIST_ICBU="LIST_ICBU";
export const GET_SINGLE_ICBU="GET_SINGLE_ICBU";
export const CREATE_ICBU="CREATE_ICBU";
export const UPDATE_ICBU="UPDATE_ICBU";


//Add Project

export const PROJECT_NAME="PROJECT_NAME";
export const SEGMENT="SEGMENT";
export const AREA="AREA";
export const PROJECT_BUSINESS_UNIT="PROJECT_BUSINESS_UNIT";
export const SITE_LOCATION="SITE_LOCATION";
export const PROJECT_INDEPENDENT_COMPANY="PROJECT_INDEPENDENT_COMPANY";

export const RESET_PROJECT_FORM = "RESET_PROJECT_FORM";
export const LIST_PROJECT = "LIST_PROJECT";
export const SHOW_ADD_PROJ_MODAL = "SHOW_ADD_PROJ_MODAL";
export const SET_EDIT_MODE = "SET_EDIT_MODE";
export const GET_SINGLE_PROJ = "GET_SINGLE_PROJ";
export const GET_SEGMENT_LIST = "GET_SEGMENT_LIST";
export const GET_IC_LIST = "GET_IC_LIST";
export const GET_BU_LIST = "GET_BU_LIST";
export const ON_CHANGE_SEGMENT = "ON_CHANGE_SEGMENT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const SHOW_ERR_MSG = "SHOW_ERR_MSG";
export const ADD_LOCATION_FIELD = "ADD_LOCATION_FIELD";

//Sub Contractor
export const VENDOR_NAME="VENDOR_NAME";
export const VENDOR_CODE="VENDOR_CODE";
export const VENDOR_EMAIL="VENDOR_EMAIL";
export const VENDOR_CONTACT_NUMBER="VENDOR_CONTACT_NUMBER";
export const VENDOR_LIST="VENDOR_LIST";
export const VENDOR_STATUS="VENDOR_STATUS";

export const LIST_VENDOR="LIST_VENDOR";
export const GET_SINGLE_VENDOR="GET_SINGLE_VENDOR";
export const UPDATE_VENDOR="UPDATE_VENDOR";
export const CREATE_VENDOR="CREATE_VENDOR";

export const SHOW_ADD_VENDOR_MODAL="SHOW_ADD_VENDOR_MODAL";
export const RESET_VENDOR_FORM="RESET_VENDOR_FORM";
export const SHOW_ADD_VENDOR_MSG="SHOW_ADD_VENDOR_MSG";

//Add Work Break
export const WORK_BREAK_PROJECT_NAME="PROJECT_NAME";
export const WBS_UPLOADED_DATA="WBS_UPLOADED_DATA";
export const RESET_WBS_FORM="RESET_WBS_FORM";
export const LIST_PROJECT_CODES="LIST_PROJECT_CODES";
export const SAVE_WBS_DATA="SAVE_WBS_DATA";
export const LIST_WBS_DATA="LIST_WBS_DATA";
// Assign Structure
export const CAPACITY="CAPACITY";
export const OVER_ALL_LENGTH="OVER_ALL_LENGTH";
export const UNDER_SLING_OVER_SLUNG="UNDER_SLING_OVER_SLUNG";
export const ESTIMATED_WEIGHT="ESTIMATED_WEIGHT";
export const DIAMENSION_LENGTH="DIAMENSION_LENGTH";
export const DIAMENSION_HEIGHT="DIAMENSION_HEIGHT";
export const DIAMENSION_WIDTH="DIAMENSION_WIDTH";
export const NUMBER_OF_COMPONENTS="NUMBER_OF_COMPONENTS";
export const LIST_ASSIGN_STRUCTURE="LIST_ASSIGN_STRUCTURE";
export const ASSIGN_STRUCTURE_MORE_PAGE="ASSIGN_STRUCTURE_MORE_PAGE";
export const CHANGE_ASSIGN_STRUCTURE_MORE_MODAL_STATUS="CHANGE_ASSIGN_STRUCTURE_MORE_MODAL_STATUS";
export const GET_ASSIGN_STRUCTURE_DATA_SINGLE="GET_ASSIGN_STRUCTURE_DATA_SINGLE";
export const LIST_ASSIGN_COMPONENT="LIST_ASSIGN_COMPONENT";
export const CHANGE_ASSIGN_COMPONENT_MORE_MODAL_STATUS="CHANGE_ASSIGN_COMPONENT_MORE_MODAL_STATUS";
export const GET_ASSIGN_COMPONENT_DATA_SINGLE="GET_ASSIGN_COMPONENT_DATA_SINGLE";
export const ASSIGN_COMPONENT_MORE_PAGE="ASSIGN_COMPONENT_MORE_PAGE";
export const SET_PROJECT_STRUCTURE_ID="SET_PROJECT_STRUCTURE_ID";
//Add Requirment

export const QUANTITY="QUANTITY";
export const REQUIRED_FOR_WORK_BREAK="REQUIRED_FOR_WORK_BREAK";
export const REQUIRED_BY="REQUIRED_BY";
export const ACTUAL_WORK_BREAK="ACTUAL_WORK_BREAK";
export const PLANNED_START_DATE="PLANNED_START_DATE";
export const ACTUAL_START_DATE_OF_USAGE="ACTUAL_START_DATE_OF_USAGE";
export const PLANNED_RELEASE_DATE="PLANNED_RELEASE_DATE";
export const EXPECTED_RELEASE_DATE="EXPECTED_RELEASE_DATE";
export const MR_NUMBER="MR_NUMBER";
export const REMARKS="REMARKS";
export const LIST_WBS_CODES="LIST_WBS_CODES";
export const SITE_REQUIRMENT_LIST="SITE_REQUIRMENT_LIST";
export const ADD_REQUIREMENT="ADD_REQUIREMENT";
export const RESET_REQUIREMENT_FORM="RESET_REQUIREMENT_FORM";

//Dispatch Management

export const SITE_NAME="SITE_NAME";
export const DATE_OF_REQUEST="DATE_OF_REQUEST";
export const REQUEST_RAISED_BY="REQUEST_RAISED_BY";
export const STRUCTURE_FAMILY = 'STRUCTURE_FAMILY';
export const QUANTITY_REQUESTED = 'QUANTITY_REQUESTED';
export const DISPATCH_ADVICE_NUMBER = 'DISPATCH_ADVICE_NUMBER';

// New Fabrication

export const DC_NUMBER = 'DC_NUMBER';
export const VENDOR = 'VENDOR';
export const DISPATCHED_DATE = 'DISPATCHED_DATE';
export const TO_SITE = 'TO_SITE';
export const QUANTITY_DISPATCHED = 'QUANTITY_DISPATCHED';
export const WORK_ORDER = 'WORK_ORDER';

//Out Source
export const MONTHLY_HIRE_CHARGES = 'MONTHLY_HIRE_CHARGES';

//Scrap

export const AUCTION_ID = 'AUCTION_ID';
export const SCRAP_RATE = 'SCRAP_RATE';

//Modification Management

export const DISPATCHED_FROM = 'DISPATCHED_FROM';
export const RECEIVED_AT = 'RECEIVED_AT';
export const LENGTH = 'LENGTH';
export const WIDTH = 'WIDTH';
export const HEIGHT = 'HEIGHT';
export const BREADTH = 'BREADTH';
export const WEIGHT = 'WEIGHT';
export const COMPONENT_NAME = 'COMPONENT_NAME';
export const COMPONENT_ID = 'COMPONENT_ID';
export const ADDITIONAL_PLATES = 'ADDITIONAL_PLATES';

//Procurement

export const FABRICATION_COST = 'FABRICATION_COST';

//OutSourcing

export const MONTHLY_RENT = 'MONTHLY_RENT';
export const CONTRACT_YEARS = 'CONTRACT_YEARS';

//TransferPrice

export const FROM_SITE = 'FROM_SITE';
export const DISPATCHED_ON = 'DISPATCHED_ON';
export const TRANSFER_PRICE = 'TRANSFER_PRICE';

// Reuse
export const THICKNESS = 'THICKNESS';
export const REUSE_WEIGHT = 'REUSE_WEIGHT';
export const PROPOSED_REUSABILITY = 'PROPOSED_REUSABILITY';
export const YEAR_OF_FABRICATION = 'YEAR_OF_FABRICATION';
export const VENDOR_DETAILS = 'VENDOR_DETAILS';
export const QR_CODE_DETAILS = 'QR_CODE_DETAILS';
export const DEPRECIATION_RATE = 'DEPRECIATION_RATE';
export const BOOK_VALUE = 'BOOK_VALUE';

//Inititing Reuse

export const DISPATCH = 'DISPATCH';

//InitiatePhysicalVerification

export const INSPECTION_ID = 'INSPECTION_ID';

//Add Structure Family
export const SET_STRUCTURE_FAMILY_EDIT_MODE = 'SET_STRUCTURE_FAMILY_EDIT_MODE';
export const RESET_CREATE_STRUCTURE_FAMILY_FORM = 'RESET_CREATE_STRUCTURE_FAMILY_FORM';
export const CHANGE_ADD_STRUCTURE_FAMILY_MODAL_STATUS = 'CHANGE_ADD_STRUCTURE_FAMILY_MODAL_STATUS';
export const STRUCTURE_FAMILY_TYPE = 'STRUCTURE_FAMILY_TYPE';
export const STRUCTURE_FAMILY_TYPE_STATUS = 'STRUCTURE_FAMILY_TYPE_STATUS';

export const SHOW_ADD_STRUCTURE_FAMILY_MSG = 'SHOW_ADD_STRUCTURE_FAMILY_MSG';
export const CHANGE_STRUCTURE_FAMILY_MODAL_STATUS = 'CHANGE_STRUCTURE_FAMILY_MODAL_STATUS';
export const ADD_STRUCTURE_FAMILY = 'ADD_STRUCTURE_FAMILY';
export const UPDATE_STRUCTURE_FAMILY_TYPE = 'UPDATE_STRUCTURE_FAMILY_TYPE';
export const LIST_STRUCTURE_FAMILY = 'LIST_STRUCTURE_FAMILY';
export const GET_STRUCTURE_FAMILY_TYPE = 'GET_STRUCTURE_FAMILY_TYPE';
export const STRUCTURE_FAMILY_STATUS = 'STRUCTURE_FAMILY_STATUS';
export const RESET_CREATE_STRUCTURE_FAMILY_TYPE_FORM = 'RESET_CREATE_STRUCTURE_FAMILY_TYPE_FORM';
export const ADD_STRUCTURE_FAMILY_TYPE = 'ADD_STRUCTURE_FAMILY_TYPE';
export const SHOW_ADD_STRUCTURE_FAMILY_MODAL = 'SHOW_ADD_STRUCTURE_FAMILY_MODAL';

//Assign Structure
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_STRUCT_LIST = "GET_STRUCT_LIST";
export const SAVE_ASSIGN_STRUCT = "SAVE_ASSIGN_STRUCT";
export const ASSIGN_STRUCT_UPLOADED_DATA = "ASSIGN_STRUCT_UPLOADED_DATA";
export const ASSIGN_FILE_UPLOAD = "ASSIGN_FILE_UPLOAD";
export const ON_CHANGE_ASSIGN_STRUCT = "ON_CHANGE_ASSIGN_STRUCT";
export const GET_ASSIGN_STRUCT_DETAILS_ID = "GET_ASSIGN_STRUCT_DETAILS_ID";
export const ASSIGN_FILE_REMOVE = "ASSIGN_FILE_REMOVE";
export const RESET_ASSIGN_STRUCT_FORM = "RESET_ASSIGN_STRUCT_FORM";

//Auth
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const RESET_LOGIN_DETAILS = 'RESET_LOGIN_DETAILS';
export const SET_PAGE_ACCESS = 'SET_PAGE_ACCESS';
export const SET_ROLE_BASED_ROUTE_ACCESS = 'SET_ROLE_BASED_ROUTE_ACCESS';

